# Generated by Django 4.1.2 on 2022-11-01 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForecastStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_city', models.CharField(blank=True, max_length=100, null=True)),
                ('search_data', django_mysql.models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_forecast_stores',
            },
        ),
        migrations.AddIndex(
            model_name='userforecaststore',
            index=models.Index(fields=['user', 'search_city'], name='user_foreca_user_id_f7f320_idx'),
        ),
    ]
